version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: ms-nginx
    volumes:
      - ./nginx/conf/microservices.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - ms-general
      - ms-user

    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - ms

  ms-general:
    build:
      context: "."
      dockerfile: ./microservices/ms-general/Dockerfile
    container_name: ms-general
    image: ms-general
    privileged: true
    command: yarn debug
    volumes:
      - /ms-general/node_modules
      - ./microservices/ms-general:/ms-general
    ports:
      - "5000:9229"
    networks:
      - ms
      - postgres

  ms-user:
    build:
      context: "."
      dockerfile: ./microservices/ms-user/Dockerfile
    container_name: ms-user
    image: ms-user
    privileged: true
    command: yarn debug
    volumes:
      - /ms-user/node_modules
      - ./microservices/ms-user:/ms-user
    ports:
      - "5001:9229"
    networks:
      - ms
      - postgres

networks:
  ms:
    name: ms
    driver: bridge
  postgres:
    name: postgres
    external: true
