FROM node:16.14.0

WORKDIR /ms-general

COPY . /ms-general

RUN ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

RUN echo "America/Sao_Paulo" > /etc/timezone

RUN npm install pm2 -g

RUN yarn install

RUN yarn build

EXPOSE 3000

EXPOSE 4000

CMD ["pm2-runtime", "./prod/server.js"]
