#!/bin/bash

docker-compose up -d

docker exec -it ms-user bash -c "yarn install"
docker exec -it ms-user bash -c "yarn migrate"
docker exec -it ms-user bash -c "yarn seed"

docker exec -it ms-general -c "yarn install"
docker exec -it ms-general -c "yarn migrate"
docker exec -it ms-general -c "yarn seed"

docker-compose -f 'docker-compose.yml'  -p 'example-express-grpc' down

docker-compose up

exit 0;